AllCops:
  TargetRubyVersion: 2.5

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
  ExcludedMethods:
    - describe
    - context

Metrics/LineLength:
  Max: 100

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    [op]

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/EmptyCaseCondition:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline
